import { createId, createOrderNumber } from "@/lib/id";
import type { OrderRecord, StoreCategory, StoreProduct, StoreSettings } from "@/lib/store/types";

export const demoStoreSettings: StoreSettings = {
  id: "default",
  cartMinimumAmountCents: 0,
};

export const demoCategories: StoreCategory[] = [
  {
    id: "cat-almacen",
    name: "Almacén",
    slug: "almacen",
    description: "Secos, conservas, aceites, harinas y básicos de góndola.",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "cat-bebidas",
    name: "Bebidas",
    slug: "bebidas",
    description: "Gaseosas, aguas, jugos y bebidas para reposición rápida.",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: "cat-limpieza",
    name: "Limpieza e higiene",
    slug: "limpieza-e-higiene",
    description: "Detergentes, lavandina, papel y cuidado del hogar.",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: "cat-snacks",
    name: "Snacks",
    slug: "snacks",
    description: "Golosinas, snacks y compra impulsiva.",
    sortOrder: 4,
    isActive: true,
  },
];

export const demoProducts: StoreProduct[] = [
  {
    id: "prod-aceite-sol",
    categoryId: "cat-almacen",
    categorySlug: "almacen",
    categoryName: "Almacén",
    name: "Aceite de girasol 900 ml",
    slug: "aceite-de-girasol-900-ml",
    brand: "Cocina Sur",
    description: "Caja mayorista x 12 unidades. Ideal para reposición semanal.",
    imageUrl:
      "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1200&q=80",
    priceCents: 324000,
    salePriceCents: 299000,
    minimumQuantity: null,
    isFeatured: true,
    isActive: true,
    availabilityNote: "Entrega en 48 hs",
    sortOrder: 1,
  },
  {
    id: "prod-fideos",
    categoryId: "cat-almacen",
    categorySlug: "almacen",
    categoryName: "Almacén",
    name: "Fideos spaghetti 500 g",
    slug: "fideos-spaghetti-500-g",
    brand: "Molino Río",
    description: "Pack mayorista x 24 unidades para góndola seca.",
    imageUrl:
      "https://images.unsplash.com/photo-1551462147-37885acc36f1?auto=format&fit=crop&w=1200&q=80",
    priceCents: 238000,
    salePriceCents: null,
    minimumQuantity: null,
    isFeatured: false,
    isActive: true,
    availabilityNote: null,
    sortOrder: 2,
  },
  {
    id: "prod-gaseosa-cola",
    categoryId: "cat-bebidas",
    categorySlug: "bebidas",
    categoryName: "Bebidas",
    name: "Gaseosa cola 2.25 L",
    slug: "gaseosa-cola-2-25-l",
    brand: "Brío",
    description: "Fardo x 6 botellas PET para alta rotación.",
    imageUrl:
      "https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=1200&q=80",
    priceCents: 412000,
    salePriceCents: 389000,
    minimumQuantity: null,
    isFeatured: true,
    isActive: true,
    availabilityNote: "Promoción de temporada",
    sortOrder: 1,
  },
  {
    id: "prod-agua",
    categoryId: "cat-bebidas",
    categorySlug: "bebidas",
    categoryName: "Bebidas",
    name: "Agua mineral 1.5 L",
    slug: "agua-mineral-1-5-l",
    brand: "Aqua Norte",
    description: "Pack x 6 unidades, exhibición refrigerada o góndola.",
    imageUrl:
      "https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=1200&q=80",
    priceCents: 185000,
    salePriceCents: null,
    minimumQuantity: null,
    isFeatured: false,
    isActive: true,
    availabilityNote: null,
    sortOrder: 2,
  },
  {
    id: "prod-lavandina",
    categoryId: "cat-limpieza",
    categorySlug: "limpieza-e-higiene",
    categoryName: "Limpieza e higiene",
    name: "Lavandina 1 L",
    slug: "lavandina-1-l",
    brand: "Blanca Total",
    description: "Caja mayorista x 12 unidades para limpieza hogar y comercio.",
    imageUrl:
      "https://images.unsplash.com/photo-1583947582886-f40ec95dd752?auto=format&fit=crop&w=1200&q=80",
    priceCents: 164000,
    salePriceCents: 149000,
    minimumQuantity: null,
    isFeatured: true,
    isActive: true,
    availabilityNote: null,
    sortOrder: 1,
  },
  {
    id: "prod-papel",
    categoryId: "cat-limpieza",
    categorySlug: "limpieza-e-higiene",
    categoryName: "Limpieza e higiene",
    name: "Papel higiénico x 4",
    slug: "papel-higienico-x-4",
    brand: "Casa Clara",
    description: "Bulto x 10 packs, alta rotación y margen estable.",
    imageUrl:
      "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=1200&q=80",
    priceCents: 278000,
    salePriceCents: null,
    minimumQuantity: null,
    isFeatured: false,
    isActive: true,
    availabilityNote: "Últimas unidades del lote",
    sortOrder: 2,
  },
  {
    id: "prod-papas",
    categoryId: "cat-snacks",
    categorySlug: "snacks",
    categoryName: "Snacks",
    name: "Papas fritas clásicas 140 g",
    slug: "papas-fritas-clasicas-140-g",
    brand: "Crunch Club",
    description: "Caja x 18 unidades para exhibición en puntera o caja.",
    imageUrl:
      "https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=1200&q=80",
    priceCents: 356000,
    salePriceCents: 332000,
    minimumQuantity: null,
    isFeatured: true,
    isActive: true,
    availabilityNote: null,
    sortOrder: 1,
  },
  {
    id: "prod-caramelos",
    categoryId: "cat-snacks",
    categorySlug: "snacks",
    categoryName: "Snacks",
    name: "Caramelos surtidos 800 g",
    slug: "caramelos-surtidos-800-g",
    brand: "Dulce Día",
    description: "Bolsa institucional para recarga de exhibidores.",
    imageUrl:
      "https://images.unsplash.com/photo-1516747773440-fd9eb4d5b5dd?auto=format&fit=crop&w=1200&q=80",
    priceCents: 214000,
    salePriceCents: null,
    minimumQuantity: null,
    isFeatured: false,
    isActive: true,
    availabilityNote: null,
    sortOrder: 2,
  },
];

export const demoOrders: OrderRecord[] = [
  {
    id: createId("order"),
    orderNumber: createOrderNumber(),
    status: "submitted",
    currencyCode: "ARS",
    subtotalCents: 688000,
    discountCents: 47000,
    totalCents: 641000,
    customerCompany: "Autoservicio Central",
    customerName: "Mariela Gómez",
    customerPhone: "+54 9 351 555 0123",
    customerEmail: "compras@autoserviciocentral.com",
    taxId: "30-71234567-8",
    deliveryCity: "Córdoba Capital",
    notes: "Entregar por la mañana.",
    whatsAppUrl: "",
    whatsAppMessage: "Pedido demo",
    source: "shop",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    items: [
      {
        id: createId("item"),
        orderId: "demo",
        productId: "prod-aceite-sol",
        productSnapshotName: "Aceite de girasol 900 ml",
        productSnapshotSku: "PERS-ACE-900",
        unitPriceCents: 324000,
        saleUnitPriceCents: 299000,
        quantity: 1,
        lineSubtotalCents: 324000,
        lineTotalCents: 299000,
      },
      {
        id: createId("item"),
        orderId: "demo",
        productId: "prod-papas",
        productSnapshotName: "Papas fritas clásicas 140 g",
        productSnapshotSku: "PERS-PAPAS-140",
        unitPriceCents: 356000,
        saleUnitPriceCents: 342000,
        quantity: 1,
        lineSubtotalCents: 364000,
        lineTotalCents: 342000,
      },
    ],
  },
];
